name: "Analyze Repository"
description: "Analyze a cloned GitHub repository via external API and update the README with results"
author: "Minwoo"

inputs:
  repo_url:
    description: "GitHub repository URL to analyze"
    required: true
  branch:
    description: "Branch name to checkout"
    required: true
  ondemand_api_key:
    description: "Sparrow On-Demand generated API key"
    required: true
  working_dir:
    description: "Directory where the repository is located (optional)"
    required: false
    default: "target-repo"

outputs:
  result_json:
    description: "Analysis result JSON string"

runs:
  using: "composite"
  steps:
    - name: Check Input values
      shell: bash
      run: |
        echo repo_url: ${{ inputs.repo_url }} \
        echo branch: ${{ inputs.branch }} \
        echo ondemand_api_key: ${{ inputs.ondemand_api_key }} \
        echo working_dir: ${{ inputs.working_dir }} 

    - name: Clone target repository (if not already present)
      shell: bash
      run: |
        if [ ! -d "${{ inputs.working_dir }}/.git" ]; then
          echo "Cloning repository into ${{ inputs.working_dir }}..."
          git clone --branch "${{ inputs.branch }}" --single-branch "${{ inputs.repo_url }}" "${{ inputs.working_dir }}"
        fi
    
    - name: debug check (Inner Action)
      shell: bash
      run: |
        echo "ls -al: " \
        ls -al \
        echo "pwd: " \
        pwd \

    - name: Run analysis script
      shell: bash
      run: bash "${{ github.action_path }}/entrypoint.sh" "${{ inputs.repo_url }}" "${{ inputs.branch }}" "${{ inputs.ondemand_api_key }}"
